server:
  port: 8760

spring:
  application:
    name: gateway  
  cloud:
    gateway:
      routes:
      - id: marlow-atm-service-1
        uri: ${ATM_SERVER:http://localhost:8092/}
        predicates:
        - Path=/api/v1/transactions/**
       
     

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
    serviceUrl: 
      defaultZone: ${EUREKA_SERVER:http://localhost:8083/eureka}
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info